goyalmunish/reminder

- README.md
Update readme with its first review.
- **Low**: Making readme better. No change in funcationality.
> Readme's first review

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- internal/models/tag.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Refactor Tag, Note, and standalone functions
- **Medium**: Refactoring might have gone wrong.
> Refactor Tag, Note, and standalone functions

- README.md
Add screen cast of basic features
- **Low**: Just adding screencast video.
> Add screen cast of basic features

- README.md
Update readme with 2nd review
- **Low**: Just updating the readme.
> Update readme with 2nd review

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- internal/models/tag.go
Refactor Note and Tag models to bring in standard Notes and Tags structures.
- **High**: Some untested functionality might break.
> Refactor Note and Tag models

- internal/models/models_test.go
- internal/models/reminder_data.go
Update ReminderData to know about data file path
- **High**: Untested functionality might break.
> Update ReminderData to know about data file path

- cmd/reminder/main.go
- internal/models/constants.go
- internal/models/models_test.go
- internal/models/reminder_data.go
- internal/models/tag.go
Remove constants.go
- **High**: Some untested functionality might break.
> Remove constants.go

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
Refactor printing stats
- **Low**: Small refactoring and addition of test cases
> Refactor printing stats

- pkg/utils/functions.go
- pkg/utils/functions_test.go
Add function to get the current terminal size
- **Low**: Almost no changes to existing functionality.
> Add function to get the current terminal size

- cmd/reminder/main.go
Use dynamic search list width
- **Medium**: Search functionality UI might break.
> Use dynamic search list width

- cmd/reminder/main.go
- internal/models/reminder_data.go
- pkg/utils/functions.go
Make the listing of notes fluid (dynamic). Fixes https://github.com/goyalmunish/reminder/issues/11
- **Medium**: Listing of notes might get impacted (say on some OSes or terminals)
> Make the listing of notes fluid (dynamic)

- cmd/reminder/main.go
- internal/models/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Add option to clear existing due date. Address https://github.com/goyalmunish/reminder/issues/24
- **Medium**: Only affects the due date functionality
> Add option to clear existing due date

- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- internal/models/tag.go
Refactor function FTagsSlugs to method tags.Slugs
- **High**: The change involves a big chunk of refactoring; some untested functionality might break.
> Refactor function FTagsSlugs to method tags.Slugs

- internal/models/models_test.go
- internal/models/reminder_data.go
- internal/models/tag.go
Refactor TagsFromIds
- **Low**: Choosing tag functionality might break.
> Refactor TagsFromIds

- internal/models/models_test.go
- internal/models/reminder_data.go
- internal/models/tag.go
Refactor TagFromSlug
- **Low**: Search functionality related to finding tag from its slug might break.
> Refactor TagFromSlug

- internal/models/models_test.go
- internal/models/reminder_data.go
- internal/models/tag.go
Refactor TagIdsForGroup
- **Low**: This will just impact tag group functionality.
> Refactor TagIdsForGroup

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
Refactor NotesWithTagId
- **High**: Almost all of the workflow will break if this goes wrong.
> Refactor NotesWithTagId

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- internal/models/tag.go
- internal/models/user.go
Refactor AddNoteComment
- **Medium**: Addition of new comments to notes might not work.
> Refactor AddNoteComment

- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
Refactor  UpateNoteText and UpdateNoteCompleteBy
- **Medium**: Notes might not get udpated.
> Refactor  UpateNoteText and UpdateNoteCompleteBy

- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
Refactor UpdateNoteTags
- **Medium**: Note might fail to be updated with tags.
> Refactor UpdateNoteTags

- cmd/reminder/main.go
- internal/models/reminder_data.go
- internal/models/tag.go
Enhance tag creation workflow. Idea is to keep the business logic and validations in right place.
- **Low**: Although it is tested thoroughly, there might still be an edge case that can use tag creation to be failing.
> Enhance tag creation workflow

- cmd/reminder/main.go
- internal/models/note.go
- internal/models/reminder_data.go
Enhance note creation workflow. Idea is to keep the business logic and validations in right place.
- **Medium**: Note creation might fail.
> Enhance note creation workflow

- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- pkg/utils/symbols.go
Refactor UpdateNoteStatus
- **Low**: Note's status might fail to update.
> Refactor UpdateNoteStatus

- internal/models/note.go
- internal/models/reminder_data.go
- internal/models/tag.go
- pkg/utils/functions.go
Be specific about warning/error messages
- **Low**: Only changes to warning/error messages.
> Be specific about warning/error messages

- cmd/reminder/main.go
- internal/models/reminder_data.go
Add automatic backup, as raised here https://github.com/goyalmunish/reminder/issues/42
- **Low**: Manual backups might fail.
> Add automatic Backup

- internal/models/comment.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Update display time format for comments
- **Low**: Might impact display of comments.
> Update display time format for comments

- cmd/reminder/main.go
- pkg/utils/bellskipper.go
- pkg/utils/functions.go
Fix bell sound and sorting under search
- **Low**: Can impact only search functionality or promptui select
> Fix bell sound and sorting under search

- cmd/reminder/main.go
- internal/models/comment.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/prompt.go
- internal/models/reminder_data.go
- internal/models/tag.go
- internal/models/user.go
Perform minor refactoring for performance
- **High**: As the changes touch almost all functionalities.
> Minor refactoring for performance

- internal/models/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Use go template to get stats report
- **Low**: Impacts only stats display functionality
> Use go template to get stats report

- internal/models/comment.go
- internal/models/reminder_data.go
Use go template for comment representation
- **Low**: Impacts only comment representation
> Use go template for comment representation

- cmd/reminder/main.go
- internal/models/reminder_data.go
Update if-clauses to adhere to Go's guard clause
- **High**: Impacting multiple functionalities.
> Update if-clauses to adhere to Go's guard clause

- internal/models/models_test.go
- internal/models/note.go
Print tags and comments title
- **Low**: Impacts only printing of a note.
> Print tags and comments title

- cmd/reminder/main.go
- internal/models/reminder_data.go
- pkg/utils/functions.go
Auto-refresh the notes list
- **High**: As this involves changes in workflow for pending/done/urgent notes.
> Auto-refresh the notes list

- README.md
Update README with change in label name from "Pending Notes" to "Urgent Notes".
- **Low**: Only updating readme.
> Update README with change in label name

- internal/models/models_test.go
- internal/models/reminder_data.go
- pkg/utils/functions.go
Cleanup UrgentNotes
- **Low**: Refactoring and addition of extra test cases
> Cleanup UrgentNotes

- cmd/reminder/main.go
- internal/models/reminder_data.go
Fix Navigation
- **Medium**: Affects navigation under "List Stuff" and "Search Notes"
> Fix Navigation

- README.md
- internal/models/reminder_data.go
Correct the tag section header
- **Low**: Just fixing a header and updating README
> Correct the tag section header

- cmd/reminder/main.go
- internal/models/reminder_data.go
Move functionality of displaying data file to DisplayDataFile
- **Low**: Only display data file functionality is impacted.
> Move functionality of displaying data file to DisplayDataFile

- internal/models/reminder_data.go
- pkg/utils/functions.go
Create soft symlink instead of hard one
- **Low**: Impacts only backups.
> Create soft symlink instead of hard one

- internal/models/models_test.go
- internal/models/note.go
Address https://github.com/goyalmunish/reminder/issues/78
- **Low**: Search functionality might break
> Add status filter provision inside search functionality

- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/symbols.go
Add functionality to registry summary
Partially addresses https://github.com/goyalmunish/reminder/issues/77
- **Low**: Adding new functionality; should not impact any existing one.
> Add functionality to registry summary

- README.md
- cmd/reminder/main.go
Rearrange the main menu
- **Low**: Just some cosmetic changes.
> Rearrange main menu

- internal/models/reminder_data.go
Fix user flow
- **Low**: Fixing a bug, impacts only the user flow.
> Fix user flow

- internal/models/note.go
Update searchable text to show main and status filters
- **Low**: Only impacts the search functionality.
> Update searchable text to show main and status filters

- internal/models/note.go
Reduce spacing in search
- **Low**: Just cosmetic changes, and impacts only search functionality
> Reduce spacing in search

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/note.go
- internal/models/reminder_data.go
Refactor name TestUrgentNotes
- **Medium**: Impacts functionality of listing notes with approaching due dates.
> Refactor name TestUrgentNotes

- cmd/reminder/main.go
- internal/models/models_test.go
- internal/models/reminder_data.go
- pkg/utils/functions_test.go
Take actions from the output of `golangci-lint run`
- **Low**: as it is around mostly handing the error
> Take actions from 'golangci-lint run'

- internal/model/model_test.go
- internal/model/reminder_data.go
Describe what happens to special characters while printing
- **Low**: Just adding comments to describe the issue and updating tests.
> Describe what happens to special characters while printing

- pkg/utils/functions.go
- pkg/utils/functions_test.go
Use `survey.Multiline` for Comments and Summary
Fixes https://github.com/goyalmunish/reminder/issues/28
- **Medium**: Impacts only Comments and Summary registration
> Use `survey.Multiline` for comments and summary

- README.md
- dev_guide.md
- scripts/build_image.sh
Update Dockerfile to push both the latest and versioned tag
- **Low**: Impacts only creation of docker image
> Update Dockerfile to push both latest and versioned tag

- scripts/build_image.sh
Fix image build script
- **Low**: Just impacts the image build script
> Fix image build script

- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
- pkg/utils/functions.go
Fix visibility of due dates and auto-year for due date
Fixes https://github.com/goyalmunish/reminder/issues/105 and https://github.com/goyalmunish/reminder/issues/104
- **Medium**: Just impacts the due date functionality
> Fix visibility of due dates and auto-year for due date

- dev_guide.md
Enhance docs
- **Low**: Just enhancing docs.
> Enhance docs

- README.md
- scripts/run_via_docker.sh
Update the `docker run` command to remove the container after use
It fixes https://github.com/goyalmunish/reminder/issues/4
- **Low**: Just updated the readme.
> Remove container after use

- internal/model/note.go
Make subject visible in Search
- **Low**: Impacts only the search functionality
> Make subject visible in Search

- cmd/reminder/main.go
- internal/model/model_test.go
- internal/model/notes_by_due_date.go
- internal/model/reminder_data.go
- pkg/utils/symbols.go
Add plan ahead functionality
If fixes https://github.com/goyalmunish/reminder/issues/112
- **Medium**: The display and list functionality for notes is touched.
> Add plan ahead functionality

- cmd/reminder/main.go
- internal/model/model_test.go
- internal/model/notes_by_due_date.go
- internal/model/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/symbols.go
Add "Plan ahead" functionality
It fixes https://github.com/goyalmunish/reminder/issues/112
- **High**: The display and list functionality for notes is touched.
> Plan ahead

- scripts/build_image.sh
Add an example on how to tag docker images
- **Low**: Just updating the readme.
> Add example on how to tag docker images

- internal/model/model_test.go
- internal/model/note.go
- internal/model/notes.go
- internal/model/reminder_data.go
Display repeat nature while listing the notes
- **Low**: Touches notes listing functionality
> Display repeat nature

- internal/model/model_test.go
- internal/model/reminder_data.go
Refactor `NotesApprachingDueDate` and tune long view
- **Medium**: Impacts notes list functionality
> Refactor `NotesApprachingDueDate` and tune long view

- README.md
- scripts/run_via_docker.sh
Update run_via_docker.sh for support fast mode
- **Low**: Touching helper script and updating README
> Update run_via_docker.sh for support fast mode

- internal/model/functions.go
- internal/model/model_test.go
- internal/model/reminder_data.go
Fix display for multi-line comments
- **Low**: Impacts printing of individual note
> Fix display for multi-line comments

- internal/model/functions.go
- internal/model/model_test.go
Fix display of multiline summary
- **Low**: Impacts notes display
> Fix display of multiline summary

- cmd/reminder/main.go
- pkg/utils/symbols.go
Use the telescope emoji for looking ahead
- **Low**: Updating an emoji
> Use telescope emoji for looking ahead

- cmd/reminder/main.go
- go.mod
- go.sum
- internal/model/comment.go
- internal/model/functions.go
- internal/model/note.go
- internal/model/notes.go
- internal/model/reminder_data.go
[Update imports for fully-qualified package name](https://github.com/goyalmunish/reminder/commit/d6af63c8b625842ccd82dbd9d45ff9f029f77862)
NA
- **Medium**: Refactor imports
> Update imports for fully-qualified package name

- Makefile
- internal/model/functions.go
- internal/model/model_test.go
- internal/model/reminder_data.go
- pkg/utils/bellskipper.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Use latest golangci-lint
NA
- **Low**: Minor refactoring
> Use latest golangci-lint

- cmd/reminder/main.go
- dev_guide.md
- internal/model/functions.go
- internal/model/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
- scripts/go_test
Add some minor fixes around printing and testing
NA
- **Low**: Can impact visibility of errors
> Add some minor fixes around printing and testing

- Makefile
- cmd/reminder/main.go
- internal/model/functions.go
- pkg/utils/functions.go
Minor enhancements
NA
- **Low**:  Minor enhancements
> Minor enhancements

- internal/model/comment.go
- internal/model/model_test.go
- internal/model/reminder_data.go
Fix auto HTML escaping of special characters
Fixes https://github.com/goyalmunish/reminder/issues/97
NA
- **Low**: Comments display is impacted (although, well tested)
> Fix auto HTML escaping of special characters

- README.md
Add version info to README
NA
- **Low**: Updating the README
> Add version info to README

- cmd/reminder/main.go
- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
Basic implementation of suspended status
NA
- **High**: Impacts almost all major functionalities
> Basic implementation of suspended status

- cmd/reminder/main.go
- internal/model/functions.go
- internal/model/model_test.go
- internal/model/note.go
- internal/model/notes.go
- internal/model/reminder_data.go
Refactor note status
NA
- **Low**: Using constants instead of strings; well tested change
> Refactor note status

- .github/workflows/release.yml
- .goreleaser.yml
- README.md
- cmd/reminder/main.go
- internal/model/note.go
- main.go
Initial setup for Goreleaser
Further check:
- https://goreleaser.com/
- https://github.com/goreleaser/goreleaser
NA
- **Low**: No impact (almost) to existing code and application flow
> Initial setup for Goreleaser

- .github/workflows/release.yml
- .goreleaser.yml
- cmd/reminder/main.go
- internal/model/reminder_data.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Refactor printing and listing of notes
NA
- **High**: Impacts listing of notes across all functionalities
> Refactor printing and listing of notes

- Dockerfile
Perform below enhancements:
- Use golang:1.19-alpine3.16 as base image
NA
- **Low**: Impacts docker build
> Update Dockerfile for golang:1.19

- cmd/reminder/main.go
- config/default.yaml
- go.mod
- internal/settings/config.go
- pkg/logger/logger.go
- pkg/logger/options.go
Refactor to inject keys to the logger instance
NA
- **Medium**: Impacts logger and viper settings
> Refactor to inject keys to logger instance

- cmd/reminder/main.go
- config/default.yaml
- internal/appinfo/options.go
- internal/model/comment.go
- internal/model/functions.go
- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
- internal/model/tag.go
- internal/model/user.go
- pkg/calendar/calendar.go
- pkg/calendar/options.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Accept tilda (~) based paths
NA
- **Low**: Impact initial configuration loading.
> Accept tilda (~) based paths

- internal/model/reminder_data.go
- pkg/calendar/calendar.go
Update error flow
NA
- **Medium**: Impacts Calendar Sync flow
> Update error flow

- internal/model/reminder_data.go
Separate out the event deletion step
NA
- **Low**: Impacts Google Calendar Sync action
> Separate out the event deletion step

- config/default.yaml
- go.mod
- internal/model/reminder_data.go
- internal/settings/config.go
- pkg/calendar/options.go
Setup dry mode for Calendar Sync
NA
- **Low**: Impacts only syncing of events to Google Calendar
> Setup dry mode for Calendar Sync

- cmd/reminder/main.go
- pkg/calendar/options.go
- pkg/logger/logger.go
Investigate logger debug mode in `LoadConfig` and `dry_mode` not getting picked up
NA
- **Low**: Just fixing `DryMode` settings
> Investigate logger debug mode in `LoadConfig` and `dry_mode` not getting picked up

- cmd/reminder/main.go
- internal/model/comment.go
- internal/model/functions.go
- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
- internal/settings/config.go
- pkg/calendar/calendar.go
- pkg/logger/logger.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Enhance logger to work in both settings with/without context
NA
- **High**: Changes touches almost all part of the app. 
> Enhance logger to work in both settings with/without context

- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
- Add note details (only safe components) to the Calendar event's description
- Adjust notification timing
NA
- **Low**: Impacts only Calendar Sync functionality
> Add note's details (only safe components) to Calendar event's description

- .github/workflows/ci.yml
- Makefile
- cmd/reminder/main.go
- internal/model/comment.go
- internal/model/comments.go
- internal/model/functions.go
- internal/model/model_test.go
- internal/model/note.go
- internal/model/reminder_data.go
- main.go
- pkg/calendar/calendar.go
- pkg/calendar/options.go
- pkg/utils/functions.go
- pkg/utils/functions_test.go
Enable calendar by default and perform some overall flow update
NA
- **High**: A large refactoring, although well-tested
> Enable calendar by default
