goyalmunish/reminder

dev_guide.md, internal/models/models_test.go, internal/models/note.go, internal/models/tag.go, internal/models/user.go
Add string representation of Tag
- **Low**: Adding string representation of Tag, without change in existing functionality.
=> Add string representation of Tag

cmd/reminder/main.go, internal/models/models_test.go, internal/models/note.go, pkg/utils/functions.go, pkg/utils/functions_test.go
Fix https://github.com/goyalmunish/reminder/issues/18
Issue: Adding character to the search field, displays a new search field unless the search field is already at bottom of the terminal window. So, the search prompt doesn't remain on the same position.
Reason: This was happening text lines overflowing the terminal width
- **Low**: Impacts only search functionality
=> Fix non-static search prompt

cmd/reminder/main.go, internal/models/models_test.go, internal/models/reminder_data.go
Remove redundant tag sort
- **Low**: Removing double sorting.
=> Remove redundant tag sort

internal/models/models_test.go, internal/models/prompt_interfaces.go, internal/models/reminder_data.go, internal/models/tag.go
Refactor FNewTag to remove its dependency on promptui.Prompt
- **Low**: Tag creation might fail.
=> Refactor FNewTag to remove its dependency on promptui.Prompt

cmd/reminder/main.go, internal/models/reminder_data.go
- Add the current tag name (slug) to the list of notes screen. This is helpful when coming out of a particular note using "Control + c" so that the user knows which tag she/he is in currently.
- Promote "Add comment" option as the first option. This will make it easier while taking down minutes of a meeting, where multiple comments are to be added regarding a single topic.
- **Low**: Changes have been tested, and no issues are expected. At max, the action of some options might get interchange.
=> Enhance user workflow

internal/models/reminder_data.go
Keep 'Exit to main menu' option at the same option number as 'Exit'
- **Log**: The action of options might get interchanged.
=> Keep 'Exit to main menu' option at the same option number as 'Exit'

pkg/utils/functions.go
Allow empty user name and email
- **Low**: User registration might fail.
=> Allow empty user name and email

internal/models/comment.go, internal/models/models_test.go, internal/models/note.go
Separate out date and text from comment. This is done to display Unix timestamps in comments in human format.
- **High**: Comments and Notes might fail to get parse and created.
=> Separate out date and text from comment

internal/models/models_test.go, internal/models/note.go, pkg/utils/functions.go, pkg/utils/functions_test.go
Change date format to DD-MM-YYYY
Reason:
- DD-MM part is significant for monthly annual repetition
- DD part is significant for monthly repetition
- DD-MM-YYYY is the default Australian date format
- **Low**: May impact "update completed by" functionality.
=> Change date format to DD-MM-YYYY

cmd/reminder/main.go, internal/models/models_test.go, internal/models/reminder_data.go, pkg/utils/bellskipper.go, pkg/utils/symbols.go
Make empty tags easy to recognize
- **Low**: Tag listing might faile.
=> Make empty tags easy to recognize

internal/models/base_struct.go, internal/models/models_test.go, internal/models/note.go, internal/models/reminder_data.go, internal/models/tag.go
Move `UpdatedAt` field to `BaseStruct`, and use it via Embedding with anonymous fields.
- **Low**: Only impact on `UpdatedAt` field.
=> Move `UpdatedAt` field to `BaseStruct`

internal/models/base_struct.go, internal/models/comment.go, internal/models/models_test.go, internal/models/note.go, internal/models/tag.go
Refactor `CreatedAt` field for models
- **Low**: Impacts only `CreatedAt` field
=> Refactor `CreatedAt` field for models

README.md, cmd/reminder/main.go, internal/models/models_test.go, internal/models/note.go, internal/models/reminder_data.go, internal/models/tag.go, pkg/utils/functions.go
Remove redundant "Add Note" and "Add Tag" options
- **Low**: Removing redundant options
=> Remove redundant "Add Note" and "Add Tag" options

internal/models/models_test.go, pkg/utils/functions.go, pkg/utils/functions_test.go
Use local time as the default
- **Low**: Impacting only time display.
=> Use local time as the default

README.md, cmd/reminder/main.go
With the merge of https://github.com/goyalmunish/reminder/pull/79, explicit functionality to show done notes is no longer required.
- **Low**: Removes only done functionality listing.
=> Remove functionality to show done notes

README.md, cmd/reminder/main.go, go.mod, go.sum, internal/models/models_test.go, internal/models/note.go, internal/models/reminder_data.go, pkg/utils/symbols.go
Add functionality to set a note as main / non-main (incidental)
Addressing part of the issue https://github.com/goyalmunish/reminder/issues/77
- **Low**: Doesn't impact existing functionality
=> Add functionality to set a note as main / non-main (incedental)

cmd/reminder/main.go, internal/models/note.go, internal/models/reminder_data.go
Further filter main notes by status
- **Medium**: Touch existing functionality of listing main notes and searching all notes
=> Further filter main notes by status

Dockerfile, Makefile, dev_guide.md
Use Go 1.18 for Docker
- **Low**: Impacts only the Docker image
=> Use Go 1.18 for Docker

internal/model/model_test.go, internal/model/note.go, internal/model/reminder_data.go, pkg/utils/functions.go
Use the current year if year part is missing
- **Low**: Impacts only the due date functionality
=> Use the current year if year part is missing

cmd/reminder/main.go, go.mod, go.sum, internal/model/reminder_data.go
Minimize printing errors outside `main.go`
- **Low**: No change of functionality, except the movement of printing of errors.
=> Minimize printing errors outside main.go

pkg/utils/functions.go
Enable vim mode by default
- **Low**: Just enabling an option.
=> Enable vim mode by default

internal/model/model_test.go, internal/model/note.go
Fix searchable text containing newlines
- **Low**: Impacts only search text functionality
=> Fix searchable text containing newlines

go.mod, go.sum
Upgrade to AlecAivazis/survey/v2 v2.3.5
NA
- **Low**: Upgrading patch version of AlecAivazis/survey
=> Upgrade to AlecAivazis/survey/v2 v2.3.5

.github/workflows/release.yml, .goreleaser.yml
Try fixing the brew tap integration
Refer: https://goreleaser.com/errors/resource-not-accessible-by-integration/
NA
- **Low**: Impacts github actions
=> Try fixing brew tap integration

internal/settings/config.go
Fallback to default configuration if app configuration is not found. At present, the configuration file makes sense only in dev workflow.
```
ERRO[0000] ❌ open ./config/default.yaml: no such file or directory panic: open ./config/default.yaml: no such file or directory
goroutine 1 [running]:
github.com/goyalmunish/reminder/cmd/reminder.init.0()
/home/runner/work/reminder/reminder/cmd/reminder/main.go:30 +0x2a4
```
NA
- **Low**: Fix the issue of an unfound configuration file.
=> Fallback to default configuration if app configuration is not found

README.md, dev_guide.md, internal/model/functions.go, internal/model/model_test.go, internal/model/note.go, internal/model/notes.go, internal/model/reminder_data.go, pkg/calendar/calendar.go
- Update doc and instructions for Calendar Sync
- Sync only the nodes with pending status and with due-date
- Introduce 30s waiting for the user before syncing
- Workaround for Cloud Calendar event time; Later, we need to make sure it to happen based on the timezone.
NA
- **Low**: Updating just docs, log messages, and an additional filter.
=> Sync only the nodes with pending status and with due-date
